const mongoose = require('mongoose');

/**
 * Module 7 — structured legal argument generation & evidence strength scoring.
 *
 * One document per case (`caseId` is unique): regenerating arguments replaces
 * the whole record (idempotent). Same lifecycle pattern as CaseAnalysis:
 *   pending → processing → completed | failed
 *
 * Stored separately from CaseAnalysis (Module 5) and Case (Module 3) —
 * arguments are a derived analytical artifact, not raw case metadata.
 */

const ARGUMENTS_STATUSES = ['pending', 'processing', 'completed', 'failed'];

const groundItemSchema = new mongoose.Schema(
  {
    title: { type: String, default: '' },
    legalGround: { type: String, default: '' },
    proceduralViolations: [{ type: String }],
    statutorySections: [{ type: String }],
    supportingLaws: [{ type: String }],
    citations: [{ type: String }],
    strength: { type: String, enum: ['High', 'Medium', 'Low'], default: 'Medium' },
  },
  { _id: false }
);

const rebuttalItemSchema = new mongoose.Schema(
  {
    title: { type: String, default: '' },
    defenseStrategy: { type: String, default: '' },
    counterArguments: [{ type: String }],
    statutoryDefenses: [{ type: String }],
    proceduralCounterpoints: [{ type: String }],
    mitigatingFactors: [{ type: String }],
  },
  { _id: false }
);

const evidenceScoreSchema = new mongoose.Schema(
  {
    documentId: { type: String, required: true },
    documentName: { type: String, default: '' },
    docType: { type: String, default: '' },
    score: { type: Number, default: 0 },
    admissibility: { type: String, enum: ['High', 'Medium', 'Low'], default: 'Medium' },
    primaryEvidence: { type: Boolean, default: false },
    reasoning: { type: String, default: '' },
  },
  { _id: false }
);

const summaryMetricsSchema = new mongoose.Schema(
  {
    totalGrounds: { type: Number, default: 0 },
    totalRebuttals: { type: Number, default: 0 },
    evidenceCount: { type: Number, default: 0 },
    evidenceHealthScore: { type: Number, default: 0 },
  },
  { _id: false }
);

const caseArgumentsSchema = new mongoose.Schema(
  {
    caseId: { type: mongoose.Schema.Types.ObjectId, ref: 'Case', required: true, unique: true, index: true },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    status: { type: String, enum: ARGUMENTS_STATUSES, default: 'pending' },
    // 'llm' when generated by Gemini, 'deterministic' when rule-based fallback
    generationMode: { type: String, default: 'deterministic' },
    arguments: {
      petitioner: [groundItemSchema],
      respondent: [rebuttalItemSchema],
    },
    evidenceScores: [evidenceScoreSchema],
    summaryMetrics: { type: summaryMetricsSchema, default: () => ({}) },
    error: { type: String, default: '' },
    generatedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

const CaseArguments = mongoose.model('CaseArguments', caseArgumentsSchema);

module.exports = CaseArguments;
module.exports.ARGUMENTS_STATUSES = ARGUMENTS_STATUSES;
