/**
 * e2e-verify.js — Automated end-to-end verification of LawGPT platform.
 *
 * Usage:  node scripts/e2e-verify.js
 *
 * Requires: backend running on :5000, frontend dev server on :5173,
 *           Chromium installed via `npx playwright install chromium`.
 */

import { chromium } from 'playwright';
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const BASE_URL = 'http://localhost:5173';
const API_URL = 'http://localhost:5000';
const TEST_EMAIL = 'test@lawgpt.local';
const TEST_PASSWORD = 'Password@123';

// Clean text-extractable legal PDF fixture (generated by
// `node backend/scripts/generateTestPdf.js`). The old inline minimal PDF had
// no text stream, so the pipeline marked documents "failed" and AI features
// 400'd with "no processed documents yet".
const FIXTURE_PDF = 'LawGPT-E2E-Writ-Petition.pdf';
const FIXTURE_PDF_PATH = join(__dirname, 'fixtures', FIXTURE_PDF);

const results = [];
let browser, context, page;

function log(step, status, detail = '') {
  const icon = status === 'PASS' ? '✅' : status === 'FAIL' ? '❌' : 'ℹ️';
  const msg = `${icon} [${step}] ${status}${detail ? ' — ' + detail : ''}`;
  console.log(msg);
  results.push({ step, status, detail });
}

async function screenshot(name) {
  const dir = join(__dirname, '..', 'test-screenshots');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, `${name}.png`);
  await page.screenshot({ path, fullPage: true });
  return path;
}

async function safeRun(stepName, fn) {
  try {
    await fn();
    return true;
  } catch (err) {
    log(stepName, 'FAIL', err.message?.slice(0, 200));
    await screenshot(`fail-${stepName.replace(/\s+/g, '-').toLowerCase()}`).catch(() => {});
    return false;
  }
}

// ─── SETUP ──────────────────────────────────────────────────────────────

async function setup() {
  browser = await chromium.launch({ headless: true });
  context = await browser.newContext({
    viewport: { width: 1280, height: 800 },
    locale: 'en-US',
  });
  page = await context.newPage();

  // Collect console errors
  page.on('console', (msg) => {
    if (msg.type() === 'error') {
      console.log(`  [console.error] ${msg.text().slice(0, 150)}`);
    }
  });

  // Collect failed network requests
  page.on('requestfailed', (req) => {
    console.log(`  [request-failed] ${req.method()} ${req.url().slice(0, 100)}`);
  });
}

async function teardown() {
  if (browser) await browser.close();
}

// ─── STEP 1: AUTHENTICATION ─────────────────────────────────────────────

async function testAuthentication() {
  console.log('\n══════════════════════════════════════════════════════');
  console.log('  STEP 1: AUTHENTICATION');
  console.log('══════════════════════════════════════════════════════');

  await page.goto(`${BASE_URL}/login`, { waitUntil: 'networkidle' });
  await screenshot('01-login-page');

  // Fill email
  const emailInput = page.locator('input[type="email"], input#email, input[name="email"]').first();
  await emailInput.waitFor({ state: 'visible', timeout: 10000 });
  await emailInput.fill(TEST_EMAIL);
  log('Login: fill email', 'PASS');

  // Fill password
  const passwordInput = page.locator('input[type="password"], input#password, input[name="password"]').first();
  await passwordInput.fill(TEST_PASSWORD);
  log('Login: fill password', 'PASS');

  await screenshot('02-login-filled');

  // Click submit
  const submitBtn = page.locator('button[type="submit"]').first();
  await submitBtn.click();
  log('Login: click Sign In', 'PASS');

  // Wait for navigation
  try {
    await page.waitForURL(/\/app/, { timeout: 15000 });
    log('Login: redirect to /app', 'PASS', page.url());
  } catch {
    log('Login: redirect to /app', 'FAIL', `Still at: ${page.url()}`);
    await screenshot('02-login-failed');
    return false;
  }

  await screenshot('03-dashboard');
  return true;
}

// ─── STEP 2: CASE CREATION ─────────────────────────────────────────────

async function testCaseCreation() {
  console.log('\n══════════════════════════════════════════════════════');
  console.log('  STEP 2: WORKSPACE & CASE CREATION');
  console.log('══════════════════════════════════════════════════════');

  // Navigate to new case page
  await page.goto(`${BASE_URL}/app/cases/new`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(1000);
  await screenshot('04-new-case-form');

  // Use a case number derived from the task spec but unique per run to avoid
  // 409 Conflict on re-runs (case numbers must be unique).
  const timestamp = Date.now().toString(36).toUpperCase();
  const caseNumber = `WP No. 2026/04/E2E${timestamp}`;

  // Fill case number
  const caseNumberInput = page.locator('input#caseNumber, input[name="caseNumber"]').first();
  if (await caseNumberInput.isVisible()) {
    await caseNumberInput.fill(caseNumber);
    log('Case: fill case number', 'PASS');
  } else {
    log('Case: fill case number', 'FAIL', 'Input not found');
  }

  // Fill title
  const titleInput = page.locator('input#title, input[name="title"]').first();
  if (await titleInput.isVisible()) {
    await titleInput.fill('Karnataka HC Writ Petition - Sangha Election');
    log('Case: fill title', 'PASS');
  } else {
    log('Case: fill title', 'FAIL', 'Input not found');
  }

  // Fill case type
  const caseTypeInput = page.locator('input#caseType, input[name="caseType"]').first();
  if (await caseTypeInput.isVisible()) {
    await caseTypeInput.fill('Writ Petition');
    log('Case: fill case type', 'PASS');
  } else {
    log('Case: fill case type', 'FAIL', 'Input not found');
  }

  // Fill description
  const descInput = page.locator('textarea#description, textarea[name="description"]').first();
  if (await descInput.isVisible()) {
    await descInput.fill('Writ Petition challenging society managing committee continuation without democratic elections.');
    log('Case: fill description', 'PASS');
  } else {
    log('Case: fill description', 'FAIL', 'Input not found');
  }

  // Fill court
  const courtInput = page.locator('input#court, input[name="court"]').first();
  if (await courtInput.isVisible()) {
    await courtInput.fill('High Court of Karnataka at Bengaluru');
    log('Case: fill court', 'PASS');
  } else {
    log('Case: fill court', 'FAIL', 'Input not found');
  }

  await screenshot('05-case-form-filled');

  // Submit
  const submitBtn = page.locator('button[type="submit"]').first();
  await submitBtn.click();
  log('Case: submit form', 'PASS');

  // Wait for case workspace to open
  try {
    await page.waitForURL(/\/app\/case\//, { timeout: 15000 });
    log('Case: workspace opened', 'PASS', page.url());
  } catch {
    log('Case: workspace opened', 'FAIL', `Still at: ${page.url()}`);
    await screenshot('05-case-creation-failed');
    return false;
  }

  await screenshot('06-case-workspace');
  return true;
}

// ─── STEP 3: DOCUMENT UPLOAD ────────────────────────────────────────────

async function testDocumentUpload() {
  console.log('\n══════════════════════════════════════════════════════');
  console.log('  STEP 3: DOCUMENT UPLOAD');
  console.log('══════════════════════════════════════════════════════');

  // Navigate to documents tab
  const currentUrl = page.url();
  const caseMatch = currentUrl.match(/\/app\/case\/([^/]+)/);
  if (!caseMatch) {
    log('Upload: find case ID', 'FAIL', 'Could not extract case ID from URL');
    return false;
  }
  const caseId = caseMatch[1];

  await page.goto(`${BASE_URL}/app/case/${caseId}/documents`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(1000);
  await screenshot('07-documents-tab');

  // Click "Add documents" or "Upload the first document" button
  const addBtn = page.locator('button').filter({ hasText: /Add documents|Upload the first document/ }).first();
  if (await addBtn.isVisible()) {
    await addBtn.click();
    log('Upload: click add documents', 'PASS');
    await page.waitForTimeout(500);
  } else {
    log('Upload: click add documents', 'FAIL', 'Button not found');
    return false;
  }

  // Use the shared legal PDF fixture (real embedded text so the pipeline
  // can extract pages and mark the document 'completed').
  const testPdfPath = FIXTURE_PDF_PATH;
  mkdirSync(join(__dirname, '..', 'test-screenshots'), { recursive: true });

  // Upload the file via the file input
  const fileInput = page.locator('input[type="file"]').first();
  await fileInput.setInputFiles(testPdfPath);
  log('Upload: select test PDF', 'PASS', FIXTURE_PDF);

  await page.waitForTimeout(500);
  await screenshot('08-file-selected');

  // Click Upload button
  const uploadBtn = page.locator('button').filter({ hasText: /Upload \d/ }).first();
  if (await uploadBtn.isVisible()) {
    await uploadBtn.click();
    log('Upload: click upload button', 'PASS');

    // Wait for upload to complete
    try {
      await page.waitForResponse(
        (resp) => resp.url().includes('/documents') && resp.status() === 200,
        { timeout: 15000 }
      );
      log('Upload: upload request completed', 'PASS');
    } catch {
      log('Upload: upload request completed', 'FAIL', 'Timeout waiting for upload response');
    }
  } else {
    log('Upload: click upload button', 'FAIL', 'Upload button not found');
  }

  await page.waitForTimeout(2000);
  await screenshot('09-after-upload');

  // Check for document in list
  const docItem = page.locator(`text=${FIXTURE_PDF}`).first();
  if (await docItem.isVisible()) {
    log('Upload: document appears in list', 'PASS', FIXTURE_PDF);
  } else {
    log('Upload: document appears in list', 'FAIL', 'Document not visible in list');
    await screenshot('09-doc-not-in-list');
  }

  // ── Poll the status badge until the document is 'completed' ──────────────
  // The Documents tab re-polls the API every 4s while a doc is pending or
  // processing, so the badge text in the row is our source of truth. Note:
  // the app's Badge component renders a <div> (not <span>) and its classes
  // don't contain the literal word "badge", so we match direct children of
  // the document row whose trimmed text is exactly a terminal status.
  let finalStatus = 'pending';
  try {
    const handle = await page.waitForFunction(
      (fname) => {
        const nodes = Array.from(document.querySelectorAll('div'));
        for (const node of nodes) {
          const text = node.textContent || '';
          if (text.includes(fname)) {
            const kids = Array.from(node.children);
            for (const kid of kids) {
              const t = (kid.textContent || '').trim().toLowerCase();
              if (t === 'completed' || t === 'failed') return t;
            }
          }
        }
        return false;
      },
      FIXTURE_PDF,
      { timeout: 240000 }
    );
    finalStatus = await handle.jsonValue();
  } catch {
    /* timeout → finalStatus stays 'pending' */
  }

  if (finalStatus === 'completed') {
    log('Upload: processing badge pending → completed', 'PASS');
  } else if (finalStatus === 'failed') {
    log('Upload: processing badge pending → completed', 'FAIL', 'Pipeline marked the fixture as failed');
  } else {
    log('Upload: processing badge pending → completed', 'FAIL', `Document stuck at '${finalStatus}' after 180s`);
  }

  await screenshot('09-document-completed');

  return caseId;
}

// ─── STEP 4: AI CASE ANALYSIS ──────────────────────────────────────────

async function testAIAnalysis(caseId) {
  console.log('\n══════════════════════════════════════════════════════');
  console.log('  STEP 4: AI CASE ANALYSIS');
  console.log('══════════════════════════════════════════════════════');

  await page.goto(`${BASE_URL}/app/case/${caseId}/ai-analysis`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(1000);
  await screenshot('10-ai-analysis-tab');

  // Click Generate/Regenerate button
  const genBtn = page.locator('button').filter({ hasText: /Generate|Regenerate/ }).first();
  if (await genBtn.isVisible()) {
    await genBtn.click();
    log('Analysis: click generate', 'PASS');

    // Wait for the full analysis view to render (Gemini round-trip via
    // python-ai can take 45-60s on this machine, so allow 180s).
    // Success = all four sections present; failure = persisted "Analysis failed".
    let analysisState = 'timeout';
    try {
      const handle = await page.waitForFunction(
        () => {
          const text = document.body.innerText;
          if (
            text.includes('Case summary') &&
            text.includes('Document timeline') &&
            text.includes('Applicable laws')
          ) {
            return 'completed';
          }
          if (text.includes('Analysis failed')) return 'failed';
          return false;
        },
        undefined,
        { timeout: 300000 }
      );
      analysisState = await handle.jsonValue();
    } catch {
      /* timeout */
    }

    if (analysisState === 'completed') {
      log('Analysis: generation completed', 'PASS');
    } else if (analysisState === 'failed') {
      log('Analysis: generation completed', 'FAIL', 'Analysis failed on python-ai');
    } else {
      log('Analysis: generation completed', 'FAIL', 'Timed out waiting for analysis view');
    }
  } else {
    log('Analysis: click generate', 'FAIL', 'Generate button not found');
  }

  await screenshot('11-ai-analysis-result');

  // Check for analysis content — expected sections once the document finished
  // processing and python-ai answered.
  const bodyText = await page.textContent('body');
  const hasSummary = bodyText.includes('Case summary');
  const hasTimeline = bodyText.includes('Document timeline');
  const hasEntities = bodyText.includes('Entities');
  const hasLaws = bodyText.includes('Applicable laws');
  const hasPageProvenance = /p\.\d|page \d/i.test(bodyText);
  const hasFailed = bodyText.includes('Analysis failed') || bodyText.includes('No analysis yet');

  if (hasFailed) {
    log('Analysis: sections', 'FAIL', 'Only failure/empty states rendered');
  } else {
    log('Analysis: summary section', hasSummary ? 'PASS' : 'FAIL');
    log('Analysis: timeline section', hasTimeline ? 'PASS' : 'FAIL');
    log('Analysis: entities section', hasEntities ? 'PASS' : 'FAIL');
    log('Analysis: applicable laws section', hasLaws ? 'PASS' : 'FAIL');
    log('Analysis: page provenance', hasPageProvenance ? 'PASS' : 'INFO', 'No p.N citations rendered');
  }
}

// ─── STEP 5: JUDGMENTS (PRECEDENT RAG) ──────────────────────────────────

async function testJudgments(caseId) {
  console.log('\n══════════════════════════════════════════════════════');
  console.log('  STEP 5: SIMILAR JUDGMENTS (PRECEDENT RAG)');
  console.log('══════════════════════════════════════════════════════');

  await page.goto(`${BASE_URL}/app/case/${caseId}/judgments`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(2000);
  await screenshot('12-judgments-tab');

  // Wait for the precedent cards (or empty state) to render — the tab
  // fires GET /precedents on mount and python-ai seeds it from the case.
  let precedentsState = 'timeout';
  try {
    const handle = await page.waitForFunction(
      () => {
        const text = document.body.innerText;
        if (text.includes('Ratio decidendi')) return 'cards';
        if (text.includes('No precedents matched')) return 'empty';
        return false;
      },
undefined,
      { timeout: 30000 }
    );
    precedentsState = await handle.jsonValue();
  } catch {
    /* timeout */
  }

  if (precedentsState === 'cards') {
    const bodyText = await page.textContent('body');
    const hasCitations = /\(\d{4}\)\s\d+\sSCC|\.\.\. PETITIONER|\bAIR\b|\bSCC\b|\bCRILJ\b/.test(bodyText);
    log('Judgments: tab loaded', 'PASS', 'Precedent cards rendered');
    log('Judgments: citations', hasCitations ? 'PASS' : 'FAIL', hasCitations ? 'Citation badges present' : 'No citation badges found');
    log('Judgments: ratio decidendi', 'PASS');
  } else if (precedentsState === 'empty') {
    log('Judgments: tab loaded', 'INFO', 'No precedents matched the case-derived query');
  } else {
    log('Judgments: tab loaded', 'FAIL', 'Timed out waiting for precedent results');
  }

  // Run a manual search and confirm the results view updates
  const searchInput = page.locator('input[type="text"], input[type="search"], input[placeholder*="search" i]').first();
  if (await searchInput.isVisible()) {
    await searchInput.fill('Section 27A Society');
    log('Judgments: search query entered', 'PASS');

    await searchInput.press('Enter');
    try {
      await page.waitForFunction(
        () => {
          const text = document.body.innerText;
          return text.includes('Showing results for:') && !text.includes('Retrieving matching precedents');
        },
        undefined,
        { timeout: 30000 }
      );
      log('Judgments: search submitted', 'PASS', 'Results updated');

      const after = await page.textContent('body');
      const resultsUpdated = after.includes('Ratio decidendi') || after.includes('No precedents matched');
      log('Judgments: filtered results render', resultsUpdated ? 'PASS' : 'FAIL');
    } catch {
      log('Judgments: search submitted', 'FAIL', 'Timed out waiting for search results');
    }
  } else {
    log('Judgments: search input', 'INFO', 'No search input found on page');
  }

  await screenshot('13-judgments-search');
}

// ─── STEP 6: ADVERSARIAL ARGUMENTS & EVIDENCE SCORING ──────────────────

async function testArguments(caseId) {
  console.log('\n══════════════════════════════════════════════════════');
  console.log('  STEP 6: ADVERSARIAL ARGUMENTS & EVIDENCE SCORING');
  console.log('══════════════════════════════════════════════════════');

  await page.goto(`${BASE_URL}/app/case/${caseId}/arguments`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(1000);
  await screenshot('14-arguments-tab');

  // Click Generate Arguments
  const genBtn = page.locator('button').filter({ hasText: /Generate arguments|Regenerate/ }).first();
  if (await genBtn.isVisible()) {
    await genBtn.click();
    log('Arguments: click generate', 'PASS');

    // Wait for the evidence meter + structured arguments to render.
    let argsState = 'timeout';
    try {
      const handle = await page.waitForFunction(
        () => {
          const text = document.body.innerText;
          if (text.includes('Evidence Strength Meter') && text.includes('Structured Arguments')) {
            return 'completed';
          }
          if (text.includes('Argument generation failed')) return 'failed';
          return false;
        },
        undefined,
        { timeout: 240000 }
      );
      argsState = await handle.jsonValue();
    } catch {
      /* timeout */
    }

    if (argsState === 'completed') {
      log('Arguments: generation completed', 'PASS');
    } else if (argsState === 'failed') {
      log('Arguments: generation completed', 'FAIL', 'Argument generation failed on python-ai');
    } else {
      log('Arguments: generation completed', 'FAIL', 'Timed out waiting for arguments view');
    }
  } else {
    log('Arguments: click generate', 'FAIL', 'Generate button not found');
  }

  await screenshot('15-arguments-result');

  // Check for evidence strength meter percentage bars and both sides.
  const bodyText = await page.textContent('body');
  const hasEvidence = bodyText.includes('Evidence Strength Meter');
  const hasPetitioner = bodyText.includes('Petitioner / Prosecution');
  const hasRespondent = bodyText.includes('Respondent / Defense');
  const hasPercentBars = /\b\d{1,3}%\b/.test(bodyText);

  // Respondent panels are behind a toggle — switch to it and confirm content.
  let respondentContent = false;
  const respTab = page.locator('button').filter({ hasText: /Respondent \/ Defense/ }).first();
  if (await respTab.isVisible()) {
    await respTab.click();
    await page.waitForTimeout(800);
    const t = await page.textContent('body');
    respondentContent = (t.match(/Defense Strategy|Counter-Arguments|Mitigating Factors/) || []).length > 0;
    // Switch back to the petitioner panel for the screenshot.
    const petTab = page.locator('button').filter({ hasText: /Petitioner \/ Prosecution/ }).first();
    if (await petTab.isVisible()) await petTab.click();
    await page.waitForTimeout(400);
  }

  const hasFailed =
    bodyText.includes('Argument generation failed') || bodyText.includes('No arguments generated');

  if (hasFailed) {
    log('Arguments: evidence strength meter', 'FAIL', 'Only failure/empty states rendered');
  } else {
    log('Arguments: evidence strength meter', hasEvidence ? 'PASS' : 'FAIL');
    log('Arguments: percentage bars', hasPercentBars ? 'PASS' : 'FAIL');
    log('Arguments: petitioner section', hasPetitioner ? 'PASS' : 'FAIL');
    log('Arguments: respondent section', hasRespondent && respondentContent ? 'PASS' : 'FAIL');
  }
}

// ─── STEP 7: INTERACTIVE CASE CHATBOT ──────────────────────────────────

async function testChat(caseId) {
  console.log('\n══════════════════════════════════════════════════════');
  console.log('  STEP 7: INTERACTIVE CASE CHATBOT');
  console.log('══════════════════════════════════════════════════════');

  await page.goto(`${BASE_URL}/app/case/${caseId}/chat`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(1000);
  await screenshot('16-chat-tab');

  // Find chat input and send a message
  const chatInput = page.locator('textarea, input[type="text"]').filter({ hasNotText: /password/i }).last();
  if (await chatInput.isVisible()) {
    await chatInput.fill('Summarize the primary relief requested in this petition.');
    log('Chat: message entered', 'PASS');

    // Find and click send button — it's an icon-only button with no text,
    // so we look for the button inside the chat input area
    const sendBtn = page.locator('.border-t.border-border button').last();
    const sendBtnAlt = page.locator('button[aria-label*="send" i], button[aria-label*="Send" i]').first();
    const btnToClick = (await sendBtn.isVisible()) ? sendBtn : sendBtnAlt;
    if (await btnToClick.isVisible()) {
      await btnToClick.click();
      log('Chat: message sent', 'PASS');

      // Wait for the assistant reply to render. The "Thinking..." bubble
      // disappears once the reply is committed; Gemini + ChromaDB retrieval
      // can take 30-60s, so allow plenty of time.
      try {
        await page.waitForFunction(
          () => {
            const text = document.body.innerText;
            const hasThinking = text.includes('Thinking...');
            const msgs = document.querySelectorAll('[class*="message"], [class*="chat"]');
            return !hasThinking && msgs.length > 1;
undefined,
          },
          { timeout: 180000 }
        );
        await page.waitForTimeout(1500);
        log('Chat: response received', 'PASS');
      } catch {
        await page.waitForTimeout(3000);
        log('Chat: response received', 'FAIL', 'Timed out waiting for assistant reply');
      }
    } else {
      log('Chat: send button', 'FAIL', 'Send button not found');
    }
  } else {
    log('Chat: input field', 'FAIL', 'Chat input not found');
  }

  await screenshot('17-chat-response');

  // Check for citations in the response. Citation cards render the "p.N"
  // badge and an "N sources cited" disclosure header when ChromaDB
  // retrieval returned page-level context.
  const bodyText = await page.textContent('body');
  const hasPageCitations = /p\.\s?\d/i.test(bodyText);
  const hasSourcesCited = /sources? cited/i.test(bodyText);
  log(
    'Chat: contains page citations',
    hasPageCitations && hasSourcesCited ? 'PASS' : 'FAIL',
    hasSourcesCited ? 'Citation cards rendered with page numbers' : 'No citation cards rendered'
  );
}

// ─── STEP 8: PDF BRIEF EXPORT ──────────────────────────────────────────

async function testPdfExport(caseId) {
  console.log('\n══════════════════════════════════════════════════════');
  console.log('  STEP 8: PDF BRIEF EXPORT');
  console.log('══════════════════════════════════════════════════════');

  await page.goto(`${BASE_URL}/app/case/${caseId}/reports`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(1000);
  await screenshot('18-reports-tab');

  // Test the API endpoint directly (since the PDF download triggers a blob)
  const bodyText = await page.textContent('body');
  const hasReportTab = bodyText.includes('Case Report') || bodyText.includes('Report') || bodyText.includes('Download');
  log('Reports: tab loaded', hasReportTab ? 'PASS' : 'FAIL');

  // Test the PDF endpoint via API with auth
  const loginResp = await page.evaluate(async () => {
    const resp = await fetch('http://localhost:5000/api/auth/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: 'test@lawgpt.local', password: 'Password@123' }),
      credentials: 'include',
    });
    return resp.json();
  });

  const accessToken = loginResp?.data?.accessToken;
  if (!accessToken) {
    log('PDF: get access token', 'FAIL', 'Could not get access token');
    return;
  }
  log('PDF: get access token', 'PASS');

  // Get the case ID from the URL
  const pdfResp = await page.evaluate(async ({ caseId, token }) => {
    const resp = await fetch(`http://localhost:5000/api/cases/${caseId}/report/pdf`, {
      headers: { Authorization: `Bearer ${token}` },
      credentials: 'include',
    });
    return {
      status: resp.status,
      contentType: resp.headers.get('content-type'),
      size: resp.headers.get('content-length'),
    };
  }, { caseId, token: accessToken });

  if (pdfResp.status === 200 && pdfResp.contentType?.includes('application/pdf')) {
    log('PDF: generate report', 'PASS', `Status: ${pdfResp.status}, Content-Type: ${pdfResp.contentType}`);
  } else {
    log('PDF: generate report', 'FAIL', `Status: ${pdfResp.status}, Content-Type: ${pdfResp.contentType}`);
  }

  // Also test metadata endpoint
  const metaResp = await page.evaluate(async ({ caseId, token }) => {
    const resp = await fetch(`http://localhost:5000/api/cases/${caseId}/report/metadata`, {
      headers: { Authorization: `Bearer ${token}` },
      credentials: 'include',
    });
    return resp.json();
  }, { caseId, token: accessToken });

  if (metaResp?.data?.sections) {
    log('PDF: metadata endpoint', 'PASS', `${metaResp.data.sections.length} sections, ${metaResp.data.completeness}% complete`);
  } else {
    log('PDF: metadata endpoint', 'FAIL', 'No sections data');
  }

  // Click the download button in the UI
  const downloadBtn = page.locator('button').filter({ hasText: /Download.*PDF|Download PDF/ }).first();
  if (await downloadBtn.isVisible()) {
    log('Reports: download button visible', 'PASS');
  } else {
    log('Reports: download button visible', 'FAIL', 'Download button not found');
  }

  await screenshot('19-reports-complete');
}

// ─── REPORT ─────────────────────────────────────────────────────────────

function printReport() {
  console.log('\n' + '═'.repeat(60));
  console.log('  E2E VERIFICATION REPORT');
  console.log('═'.repeat(60));

  const passed = results.filter((r) => r.status === 'PASS').length;
  const failed = results.filter((r) => r.status === 'FAIL').length;
  const info = results.filter((r) => r.status === 'INFO').length;

  console.log(`\n  Total: ${results.length} checks`);
  console.log(`  ✅ Passed: ${passed}`);
  console.log(`  ❌ Failed: ${failed}`);
  console.log(`  ℹ️  Info: ${info}`);
  console.log('');

  if (failed > 0) {
    console.log('  FAILED CHECKS:');
    results
      .filter((r) => r.status === 'FAIL')
      .forEach((r) => {
        console.log(`    ❌ [${r.step}] ${r.detail || 'No detail'}`);
      });
  }

  console.log('\n' + '═'.repeat(60));

  // Write report to file
  const reportPath = join(__dirname, '..', 'test-screenshots', 'e2e-report.json');
  mkdirSync(join(__dirname, '..', 'test-screenshots'), { recursive: true });
  writeFileSync(reportPath, JSON.stringify({ summary: { passed, failed, info, total: results.length }, results }, null, 2));
  console.log(`\n  Full report: ${reportPath}`);
  console.log(`  Screenshots: ${join(__dirname, '..', 'test-screenshots')}`);
}

// ─── MAIN ───────────────────────────────────────────────────────────────

async function main() {
  console.log('LawGPT E2E Verification Suite');
  console.log('━'.repeat(40));

  await setup();

  try {
    // Step 1: Authentication
    const authOk = await testAuthentication();
    if (!authOk) {
      log('E2E ABORTED', 'FAIL', 'Authentication failed — cannot proceed');
      return;
    }

    // Step 2: Case Creation
    const caseCreated = await testCaseCreation();
    if (!caseCreated) {
      log('E2E ABORTED', 'FAIL', 'Case creation failed — cannot proceed');
      return;
    }

    // Extract caseId from URL
    const caseMatch = page.url().match(/\/app\/case\/([^/]+)/);
    const caseId = caseMatch?.[1];

    // Step 3: Document Upload
    const uploadedCaseId = await testDocumentUpload();
    const finalCaseId = uploadedCaseId || caseId;

    // Step 4: AI Analysis
    await testAIAnalysis(finalCaseId);

    // Step 5: Judgments
    await testJudgments(finalCaseId);

    // Step 6: Arguments
    await testArguments(finalCaseId);

    // Step 7: Chat
    await testChat(finalCaseId);

    // Step 8: PDF Export
    await testPdfExport(finalCaseId);

  } catch (err) {
    log('UNEXPECTED ERROR', 'FAIL', err.message);
    console.error(err.stack);
  } finally {
    printReport();
    await teardown();
  }
}

main();
