from typing import List

from pydantic import BaseModel, Field

from .analysis_schemas import AnalysisDocumentInput


class ArgumentsRequest(BaseModel):
    """Module 7 — structured legal argument generation request.

    The backend streams the case's authorityized analysis (summary + key points +
    laws) and document page units here; this service never touches MongoDB or
    the uploads filesystem. `documents` reuses the Module 5 input shape so the
    backend can assemble the payload exactly like it does for analysis.
    """

    caseId: str
    caseSummary: str = ""
    keyPoints: List[str] = []
    laws: List[dict] = Field(default_factory=lambda: [])
    documents: List[AnalysisDocumentInput] = []


class GroundItem(BaseModel):
    """One **Petitioner / Prosecution** ground: legal ground, procedural
    violations attributed to the opposing party, statutes relied upon, and
    supporting precedent citations."""

    title: str = ""
    legalGround: str = ""
    proceduralViolations: List[str] = []
    statutorySections: List[str] = []
    supportingLaws: List[str] = []
    citations: List[str] = []
    strength: str = "Medium"


class RebuttalItem(BaseModel):
    """One **Respondent / Defense** rebuttal: defense strategy, counter-
    arguments, statutory defenses, procedural counter-points, and mitigating
    factors."""

    title: str = ""
    defenseStrategy: str = ""
    counterArguments: List[str] = []
    statutoryDefenses: List[str] = []
    proceduralCounterpoints: List[str] = []
    mitigatingFactors: List[str] = []


class StructuredArguments(BaseModel):
    petitioner: List[GroundItem] = []
    respondent: List[RebuttalItem] = []


class EvidenceScore(BaseModel):
    """Per-document evidence strength score (0-100%), an admissibility rating
    (High/Medium/Low), whether it is the primary evidence, and qualitative reasoning."""

    documentId: str
    documentName: str = ""
    docType: str = ""
    score: int = Field(ge=0, le=100)
    admissibility: str = "Medium"  # High | Medium | Low
    primaryEvidence: bool = False
    reasoning: str = ""


class SummaryMetrics(BaseModel):
    totalGrounds: int = 0
    totalRebuttals: int = 0
    evidenceCount: int = 0
    evidenceHealthScore: float = 0.0


class ArgumentsResult(BaseModel):
    arguments: StructuredArguments = Field(default_factory=StructuredArguments)
    evidenceScores: List[EvidenceScore] = []
    summaryMetrics: SummaryMetrics = Field(default_factory=SummaryMetrics)
    # 'llm' when generated by Gemini via llm_service.generate_json() and
    # 'deterministic' when the key/LLM was unavailable and the rule-based
    # fallback produced the structure (acceptance-testable without an API key).
    generationMode: str = "llm"